$ErrorActionPreference = "Stop"

function Normalize-BaseUrl {
  param(
    [string]$BaseUrl
  )

  if (-not $BaseUrl) {
    return ""
  }

  return $BaseUrl.Trim().TrimEnd("/")
}

function Get-PrimaryLanIp {
  try {
    $defaultRoute = Get-NetRoute -DestinationPrefix "0.0.0.0/0" |
      Sort-Object RouteMetric, InterfaceMetric |
      Select-Object -First 1

    if ($defaultRoute) {
      $ip = Get-NetIPAddress -InterfaceIndex $defaultRoute.InterfaceIndex -AddressFamily IPv4 |
        Where-Object { $_.IPAddress -notlike "127.*" -and $_.IPAddress -notlike "169.254*" } |
        Select-Object -First 1 -ExpandProperty IPAddress

      if ($ip) {
        return $ip
      }
    }
  } catch {
  }

  $fallback = Get-NetIPAddress -AddressFamily IPv4 |
    Where-Object {
      $_.IPAddress -match "^(10\\.|192\\.168\\.|172\\.(1[6-9]|2[0-9]|3[0-1])\\.)" -and
      $_.IPAddress -notlike "127.*" -and
      $_.IPAddress -notlike "169.254*"
    } |
    Select-Object -First 1 -ExpandProperty IPAddress

  if (-not $fallback) {
    throw "No LAN IPv4 address available for Android testing."
  }

  return $fallback
}

function Resolve-NativeDebugApiBaseUrl {
  $explicitNativeApiBaseUrl = Normalize-BaseUrl $env:NEXT_PUBLIC_NATIVE_DEFAULT_API_BASE_URL
  if ($explicitNativeApiBaseUrl) {
    return $explicitNativeApiBaseUrl
  }

  $lanIp = Get-PrimaryLanIp
  return ("http://{0}:3006" -f $lanIp)
}

function Get-GradleCommand {
  param(
    [string]$AndroidProjectRoot
  )

  $wrapperPropsPath = Join-Path $AndroidProjectRoot "gradle\\wrapper\\gradle-wrapper.properties"
  $wrapperProps = Get-Content $wrapperPropsPath -Raw
  $distributionUrlMatch = [regex]::Match($wrapperProps, "distributionUrl=(.+)")

  if (-not $distributionUrlMatch.Success) {
    throw "Unable to locate Gradle distribution URL."
  }

  $distributionUrl = $distributionUrlMatch.Groups[1].Value.Trim().Replace("\:", ":")
  $versionMatch = [regex]::Match($distributionUrl, "gradle-([0-9.]+)-(bin|all)\.zip")

  if (-not $versionMatch.Success) {
    throw "Unable to parse Gradle version from distribution URL: $distributionUrl"
  }

  $gradleVersion = $versionMatch.Groups[1].Value
  $cachedGradle = Get-ChildItem (Join-Path $env:USERPROFILE ".gradle\\wrapper\\dists") -Recurse -Filter gradle.bat -ErrorAction SilentlyContinue |
    Where-Object { $_.FullName -like "*gradle-$gradleVersion*" } |
    Select-Object -First 1

  if ($cachedGradle) {
    return $cachedGradle.FullName
  }

  $gradleRoot = Join-Path $env:LOCALAPPDATA "Gradle"
  $gradleHome = Join-Path $gradleRoot ("gradle-{0}" -f $gradleVersion)
  $gradleCmd = Join-Path $gradleHome "bin\\gradle.bat"

  if (-not (Test-Path $gradleCmd)) {
    New-Item -ItemType Directory -Force -Path $gradleRoot | Out-Null
    $gradleZip = Join-Path $env:TEMP ("gradle-{0}.zip" -f $gradleVersion)
    Invoke-WebRequest -Uri $distributionUrl -OutFile $gradleZip
    Expand-Archive -Path $gradleZip -DestinationPath $gradleRoot -Force
  }

  if (-not (Test-Path $gradleCmd)) {
    throw "Gradle command not found at: $gradleCmd"
  }

  return $gradleCmd
}

$projectRoot = Split-Path -Parent $PSScriptRoot
Set-Location $projectRoot

# Refresh Android launcher assets before packaging so the APK uses the latest app logo.
$updateIconsScript = Join-Path $PSScriptRoot "update-android-icons.ps1"
if (Test-Path $updateIconsScript) {
  Write-Host "Refreshing Android app icon assets..."
  & $updateIconsScript
}

if (-not $env:ANDROID_SDK_ROOT) {
  $env:ANDROID_SDK_ROOT = Join-Path $env:LOCALAPPDATA "Android\\Sdk"
}
if (-not $env:ANDROID_HOME) {
  $env:ANDROID_HOME = $env:ANDROID_SDK_ROOT
}
if (-not $env:JAVA_HOME) {
  $studioCmd = Get-Command studio64.exe -ErrorAction SilentlyContinue
  if ($studioCmd) {
    $studioRoot = Split-Path -Parent (Split-Path -Parent $studioCmd.Source)
    $studioJbr = Join-Path $studioRoot "jbr"
    if (Test-Path (Join-Path $studioJbr "bin\\java.exe")) {
      $env:JAVA_HOME = $studioJbr
    }
  }

  if (-not $env:JAVA_HOME) {
    $javaExe = (Get-Command java.exe).Source
    $env:JAVA_HOME = Split-Path -Parent (Split-Path -Parent $javaExe)
  }
}

if (-not (Test-Path "android")) {
  npx cap add android
}

$browserApiBaseUrl = Normalize-BaseUrl $env:NEXT_PUBLIC_API_BASE_URL
$nativeApiBaseUrl = Resolve-NativeDebugApiBaseUrl
$env:NEXT_PUBLIC_NATIVE_DEFAULT_API_BASE_URL = $nativeApiBaseUrl

if ($browserApiBaseUrl) {
  Write-Host "Using web API base URL from environment: $browserApiBaseUrl"
} else {
  Write-Host "No web API base URL override provided. Browser build will use same-origin /api when opened in a browser."
}

Write-Host "Debug APK native API base URL: $nativeApiBaseUrl"

$sdkDirEscaped = $env:ANDROID_SDK_ROOT.Replace("\", "\\")
@(
  "## This file is auto-generated by web/scripts/build-android-debug.ps1",
  "sdk.dir=$sdkDirEscaped"
) | Set-Content -Path "android\\local.properties" -Encoding UTF8

npm run build:export
npx cap sync android

$versionName = "dev"
$buildGradle = Get-Content "android\\app\\build.gradle" -Raw
$versionMatch = [regex]::Match($buildGradle, 'versionName\s+"([^"]+)"')
if ($versionMatch.Success) {
  $versionName = $versionMatch.Groups[1].Value
}

Push-Location "android"
try {
  $gradleCmd = Get-GradleCommand -AndroidProjectRoot $PWD.Path
  & $gradleCmd :app:assembleDebug --offline

  if ($LASTEXITCODE -ne 0) {
    throw "Gradle assembleDebug failed with exit code $LASTEXITCODE"
  }
} finally {
  Pop-Location
}

$sourceApk = Join-Path $projectRoot "android\\app\\build\\outputs\\apk\\debug\\app-debug.apk"
if (-not (Test-Path $sourceApk)) {
  throw "APK not found at: $sourceApk"
}

$artifactDir = Join-Path $projectRoot "dist-apk"
New-Item -ItemType Directory -Force -Path $artifactDir | Out-Null

$targetApk = Join-Path $artifactDir ("wotty-android-debug-{0}.apk" -f $versionName)
Copy-Item -Path $sourceApk -Destination $targetApk -Force

Write-Host "APK generated: $targetApk"
